name: Lint

on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          architecture: x64
      - name: Checkout pybackpack
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
